import type {
  BirthDecision,
  FetalMeasure,
  GynecologyObstetricsServiceItem,
  HemorrhageSafetyItem,
  LaborObservation,
  NewbornTransitionItem,
  ObstetricVigilanceItem,
  PostpartumItem,
  PregnancyEpisode,
  PrenatalEvent,
  ReproductiveHealthEvent,
} from "./types";

const observed = { origin: "observed", clinicalStatus: "validated" } as const;

export const syntheticPregnancyEpisode: PregnancyEpisode = {
  ...observed,
  episodeReference: "EpisodeOfCare/pregnancy-synthetic-1",
  maternalReference: "Patient/mother-synthetic-1",
  fetusReferences: ["RelatedPerson/fetus-a-synthetic"],
  gestationalAge: "31 SA + 4 j",
  datingBasis: "Échographie du premier trimestre documentée",
  estimatedDueDate: "2025-10-12",
  revisedFrom: "DDR estimée · révision tracée le 2025-03-18",
  parity: "G2 P1",
  recordedAt: "2025-08-14T08:30:00Z",
  sourceReference: "Observation/gestational-age-synthetic",
};

export const syntheticVigilanceItems: ObstetricVigilanceItem[] = [
  {
    id: "pressure",
    label: "Pression artérielle à recontrôler",
    detail: "Mesure récente au-dessus de la cible documentée.",
    severity: "warning",
    dueAt: "2025-08-14T09:15:00Z",
    owner: "Équipe obstétricale synthétique",
    origin: "observed",
    clinicalStatus: "warning",
    sourceReference: "Observation/bp-synthetic",
  },
  {
    id: "growth",
    label: "Croissance fœtale à confirmer",
    detail: "Estimation préliminaire, contrôle planifié.",
    severity: "information",
    dueAt: "2025-08-21",
    owner: "Imagerie synthétique",
    origin: "projected",
    clinicalStatus: "preliminary",
    sourceReference: "Task/fetal-growth-synthetic",
  },
];

export const syntheticReproductiveEvents: ReproductiveHealthEvent[] = [
  {
    ...observed,
    id: "screening",
    at: "2023-09-08",
    kind: "screening",
    label: "Dépistage documenté",
    detail: "Résultat validé.",
    visibility: "standard",
    sourceReference: "DiagnosticReport/screening-synthetic",
  },
  {
    origin: "patient-reported",
    clinicalStatus: "preliminary",
    id: "cycle",
    at: "2024-11-12",
    kind: "cycle",
    label: "Symptômes cycliques rapportés",
    detail: "Information déclarée, non confirmée.",
    visibility: "sensitive",
    sourceReference: "QuestionnaireResponse/cycle-synthetic",
  },
  {
    ...observed,
    id: "contraception",
    at: "2025-01-08",
    kind: "contraception",
    label: "Projet contraceptif archivé",
    detail: "Contenu restreint au rôle autorisé.",
    visibility: "restricted",
    sourceReference: "CarePlan/contraception-synthetic",
  },
  {
    ...observed,
    id: "procedure",
    at: "2025-04-22",
    kind: "procedure",
    label: "Procédure gynécologique",
    detail: "Compte rendu amendé disponible.",
    visibility: "standard",
    clinicalStatus: "amended",
    sourceReference: "Procedure/gynecology-synthetic",
  },
];

export const syntheticPrenatalEvents: PrenatalEvent[] = [
  {
    ...observed,
    id: "booking",
    gestationalAge: "10 SA",
    at: "2025-03-16",
    kind: "visit",
    label: "Ouverture du suivi",
    detail: "Contexte et facteurs documentés.",
    windowStatus: "complete",
    sourceReference: "Encounter/booking-synthetic",
  },
  {
    ...observed,
    id: "scan",
    gestationalAge: "12 SA + 2 j",
    at: "2025-03-30",
    kind: "imaging",
    label: "Datation échographique",
    detail: "Terme révisé et provenance conservée.",
    windowStatus: "complete",
    sourceReference: "DiagnosticReport/dating-synthetic",
  },
  {
    origin: "imported",
    clinicalStatus: "preliminary",
    id: "screening",
    gestationalAge: "22 SA",
    at: "2025-06-08",
    kind: "screening",
    label: "Dépistage importé",
    detail: "Résultat externe à confirmer.",
    windowStatus: "current",
    sourceReference: "DocumentReference/screening-synthetic",
  },
  {
    origin: "projected",
    clinicalStatus: "unknown",
    id: "growth",
    gestationalAge: "32 SA",
    at: "2025-08-21",
    kind: "imaging",
    label: "Contrôle de croissance",
    detail: "Fenêtre planifiée, résultat non disponible.",
    windowStatus: "upcoming",
    sourceReference: "ServiceRequest/growth-synthetic",
  },
];

export const syntheticFetalMeasures: FetalMeasure[] = [
  {
    ...observed,
    id: "heart-rate",
    fetusReference: "RelatedPerson/fetus-a-synthetic",
    label: "Fréquence cardiaque",
    value: "148/min",
    reference: "Référence locale documentée",
    interpretation: "within",
    sourceReference: "Observation/fhr-synthetic",
  },
  {
    origin: "derived",
    clinicalStatus: "preliminary",
    id: "weight",
    fetusReference: "RelatedPerson/fetus-a-synthetic",
    label: "Poids estimé",
    value: "1 420 g",
    reference: "p12 · courbe 2026.1",
    interpretation: "borderline",
    sourceReference: "Observation/efw-synthetic",
  },
  {
    origin: "imported",
    clinicalStatus: "unknown",
    id: "doppler",
    fetusReference: "RelatedPerson/fetus-a-synthetic",
    label: "Doppler",
    reference: "Compte rendu attendu",
    interpretation: "unknown",
    sourceReference: "DiagnosticReport/doppler-synthetic",
  },
];

export const syntheticLaborObservations: LaborObservation[] = [
  {
    ...observed,
    id: "labor-0",
    at: "2025-10-01T08:00:00Z",
    elapsedMinutes: 0,
    cervicalDilation: 3,
    fetalHeartRate: 142,
    contractions: 2,
    membraneStatus: "Intactes",
    sourceReference: "Observation/labor-0-synthetic",
  },
  {
    ...observed,
    id: "labor-1",
    at: "2025-10-01T09:00:00Z",
    elapsedMinutes: 60,
    cervicalDilation: 4,
    fetalHeartRate: 147,
    contractions: 3,
    membraneStatus: "Intactes",
    sourceReference: "Observation/labor-1-synthetic",
  },
  {
    ...observed,
    id: "labor-2",
    at: "2025-10-01T10:00:00Z",
    elapsedMinutes: 120,
    cervicalDilation: 6,
    fetalHeartRate: 152,
    contractions: 4,
    membraneStatus: "Rompues · heure documentée",
    sourceReference: "Observation/labor-2-synthetic",
  },
  {
    origin: "observed",
    clinicalStatus: "preliminary",
    id: "labor-3",
    at: "2025-10-01T11:00:00Z",
    elapsedMinutes: 180,
    cervicalDilation: 7,
    fetalHeartRate: 165,
    contractions: 4,
    membraneStatus: "Rompues",
    sourceReference: "Observation/labor-3-synthetic",
  },
];

export const syntheticBirthDecision: BirthDecision = {
  decision: "Revue du mode d’accouchement",
  indication: "Progression et rythme fœtal à réévaluer",
  decidedAt: "2025-10-01T11:05:00Z",
  targetAt: "2025-10-01T11:25:00Z",
  owner: "Obstétricien synthétique",
  readiness: [
    { id: "team", label: "Équipe informée", status: "ready" },
    { id: "consent", label: "Consentement", status: "pending" },
    { id: "theatre", label: "Salle", status: "ready" },
    { id: "newborn", label: "Accueil du nouveau-né", status: "ready" },
  ],
  origin: "observed",
  clinicalStatus: "preliminary",
  sourceReference: "Task/birth-decision-synthetic",
};

export const syntheticHemorrhageItems: HemorrhageSafetyItem[] = [
  {
    ...observed,
    id: "risk",
    label: "Risque hémorragique",
    kind: "risk",
    status: "triggered",
    detail: "Facteur de risque documenté.",
    sourceReference: "RiskAssessment/hemorrhage-synthetic",
  },
  {
    ...observed,
    id: "access",
    label: "Accès veineux",
    kind: "preparation",
    status: "ready",
    sourceReference: "Procedure/iv-synthetic",
  },
  {
    origin: "projected",
    clinicalStatus: "preliminary",
    id: "blood",
    label: "Disponibilité des produits",
    kind: "preparation",
    status: "pending",
    detail: "Confirmation attendue.",
    sourceReference: "Task/blood-products-synthetic",
  },
  {
    ...observed,
    id: "loss",
    label: "Quantification des pertes",
    kind: "response",
    status: "ready",
    detail: "Mesure active, aucune valeur simulée.",
    sourceReference: "Observation/blood-loss-synthetic",
  },
];

export const syntheticNewbornItems: NewbornTransitionItem[] = [
  {
    ...observed,
    id: "minute-1",
    newbornReference: "Patient/newborn-synthetic-1",
    minute: "1 min",
    label: "Adaptation initiale",
    value: "Score documenté : 7",
    status: "support",
    sourceReference: "Observation/apgar-1-synthetic",
  },
  {
    ...observed,
    id: "minute-5",
    newbornReference: "Patient/newborn-synthetic-1",
    minute: "5 min",
    label: "Réévaluation",
    value: "Score documenté : 9",
    status: "normal",
    sourceReference: "Observation/apgar-5-synthetic",
  },
  {
    origin: "projected",
    clinicalStatus: "unknown",
    id: "feeding",
    newbornReference: "Patient/newborn-synthetic-1",
    minute: "Après stabilisation",
    label: "Alimentation",
    status: "unknown",
    sourceReference: "CarePlan/newborn-feeding-synthetic",
  },
];

export const syntheticPostpartumItems: PostpartumItem[] = [
  {
    ...observed,
    id: "maternal-vitals",
    actor: "mother",
    label: "Surveillance maternelle",
    detail: "Paramètres documentés.",
    status: "complete",
    visibility: "standard",
    sourceReference: "Observation/postpartum-mother-synthetic",
  },
  {
    origin: "patient-reported",
    clinicalStatus: "preliminary",
    id: "mood",
    actor: "mother",
    label: "Santé mentale",
    detail: "Réponse sensible, accès contrôlé.",
    status: "follow-up",
    visibility: "sensitive",
    sourceReference: "QuestionnaireResponse/mood-synthetic",
  },
  {
    ...observed,
    id: "feeding",
    actor: "dyad",
    label: "Soutien à l’alimentation",
    detail: "Objectif partagé mère–nouveau-né.",
    status: "due",
    visibility: "standard",
    sourceReference: "CarePlan/feeding-synthetic",
  },
  {
    origin: "projected",
    clinicalStatus: "unknown",
    id: "visit",
    actor: "newborn",
    label: "Contrôle néonatal",
    status: "unavailable",
    visibility: "standard",
    sourceReference: "Appointment/newborn-followup-synthetic",
  },
];

export const syntheticServiceItems: GynecologyObstetricsServiceItem[] = [
  {
    id: "GO-020",
    label: "Consultation prénatale",
    duration: "30 min",
    level: "essential",
    sourceReference: "HealthcareService/gynecology-obstetrics-synthetic",
  },
  {
    id: "GO-040",
    label: "Surveillance du travail",
    duration: "Continu",
    level: "reference",
    sourceReference: "HealthcareService/gynecology-obstetrics-synthetic",
  },
  {
    id: "GO-050",
    label: "Revue postpartum",
    duration: "30 min",
    level: "essential",
    sourceReference: "HealthcareService/gynecology-obstetrics-synthetic",
  },
];
